### ISSUE TITLE
How to get list of top packages?

### ISSUE THREAD

**Issue by cormullion** [JuliaComputing/JuliaHub#105]
Is there an easy way to get a list of the top 20  or Top 100  packages  (by stars, for example)?

**Comment by pfitzseb** [comment]
https://juliahub.com/ui/Packages is sorted by stars, so you can use that if you just want to browse packages. Otherwise, feel free to use the https://juliahub.com/app/packages/info endpoint to get all indexed packages -- you can sort them however you like afterwards ;).

**Comment by cormullion** [comment]
Thanks, I managed it eventually!

||name|stars|
|:--|:--|--:|
|1| julia|33116|
|2| Flux|2904|
|3| Pluto|2611|
|4| IJulia|2206|
|5| DifferentialEquations|1700|
|6| Gadfly|1632|
|7| Gen|1527|
|8| JuMP|1396|
|9| Knet|1260|
|10| Plots|1233|
|11| Genie|1207|
|12| Turing|1172|
|13| MLJ|1000|
|14| PyCall|994|
|15| DataFrames|962|
|16| Zygote|945|
|17| TensorFlow|823|
|18| Makie|797|
|19| PackageCompiler|786|
|20| UnicodePlots|726|
|21| Revise|713|
|22| Optim|681|
|23| Distributions|670|
|24| JuliaDB|655|
|25| DSGE|632|
|26| DashBootstrapComponents|630|
|27| Cxx|621|
|28| LightGraphs|620|
|29| ModelingToolkit|566|
|30| Weave|561|
|31| Yao|517|
|32| OnlineStats|510|
|33| Symbolics|486|
|34| DiffEqFlux|484|
|35| OhMyREPL|476|
|36| ForwardDiff|471|
|37| Images|438|
|38| DataStructures|431|
|39| JuliaZH|428|
|40| Convex|421|
|41| ScikitLearn|421|
|42| Franklin|420|
|43| JuDoc|420|
|44| DiffEqTutorials|415|
|45| SciMLTutorials|415|
|46| Interact|411|
|47| DecentralizedInternet|407|
|48| Oceananigans|406|
|49| CUDAnative|393|
|50| Documenter|391|
|51| HTTP|389|
|52| CUDA|387|
|53| DynamicalSystems|386|
|54| DashTable|385|
|55| ProgressMeter|385|
|56| Lazy|378|
|57| StaticArrays|376|
|58| DrWatson|375|
|59| MXNet|369|
|60| GLM|365|
|61| QuantEcon|365|
|62| PyPlot|348|
|63| POMDPs|345|
|64| ApproxFun|336|
|65| LoopVectorization|335|
|66| PkgTemplates|332|
|67| TimerOutputs|330|
|68| StatsBase|328|
|69| Catlab|327|
|70| QuantumOptics|313|
|71| BenchmarkTools|312|
|72| NeuralNetDiffEq|303|
|73| NeuralPDE|303|
|74| Luxor|302|
|75| TextAnalysis|301|
|76| Cassette|297|
|77| Javis|296|
|78| Grassmann|291|
|79| Query|291|
|80| Latexify|290|
|81| GR|287|
|82| CuArrays|283|
|83| Unitful|280|
|84| Debugger|279|
|85| Literate|277|
|86| ClimateMachine|269|
|87| Dagger|268|
|88| Interpolations|268|
|89| DataFramesMeta|267|
|90| Blink|266|
|91| ControlSystems|264|
|92| OpticSim|262|
|93| Bio|259|
|94| MixedModels|259|
|95| Parameters|259|
|96| HDF5|258|
|97| JLD2|254|
|98| Measurements|254|
|99| StatPlots|254|
|100| StatsPlots|254|
