### ISSUE TITLE
Links to documentation broken

### ISSUE THREAD

**Issue by jonas-schulze** [JuliaComputing/JuliaHub#106]
Searching for a package and clicking on its name leads to a broken link. It misses the server part:

* https://juliahub.com/ui/Documentation?q=slurm leads to
* https://docs/ClusterManagers/2gedf/0.4.0 instead of
* https://juliahub.com/docs/ClusterManagers/2gedf/0.4.0

**Comment by pfitzseb** [comment]
Thanks for the report! Fix is deployed.
