### ISSUE TITLE
Pluto:  variable interpolation error

### ISSUE THREAD

**Issue by paradocs** [JuliaComputing/JuliaHub#108]
Greetings,
1) Thank you for the PlutoCon presentation.
2) I am looking to pre-pay for students to
to use Pluto notebooks. How can I set up
accounts linked to my credit card?
3) On JuliaHub my notebook is not working
to allow  variable insertion in mark down.
Is this a version problem?  My code works 
with Julia v"1.6.0",  "PlutoUI" v"0.7.6",
and Pluto v0.14.1
My code is here:
https://github.com/paradocs/Pluto.Edu/blob/main=%3E/engPartsOfSpeech.10.paradocs.jl
Best Wishes paradocs.home@gmail.com David Marc Tan Creti
![2021-04-13-005139_1280x1024_scrot](https://user-images.githubusercontent.com/1009384/114504838-1c5bc080-9bf5-11eb-92eb-99c2465bd758.png)
![2021-04-13-005130_1280x1024_scrot](https://user-images.githubusercontent.com/1009384/114504853-21b90b00-9bf5-11eb-88a9-75077ae11446.png)

**Comment by aviks** [comment]
Note that JuliaHub currently supports Julia 1.5 only . We will move to 1.6 in a few days. We also have a slightly older Pluto version, which should get updated in a day or two. Hopefully with these changes, the problem goes away. We'll investigate if not,

**Comment by pfitzseb** [comment]
Pretty sure you're running a different version locally. In the checked in notebook you define `word1List` but try to access `posList`. Your code works fine on JuliaHub when defining the word list as `posList` instead.
