### ISSUE TITLE
Build package page before adding to search result

### ISSUE THREAD

**Issue by fredrikekre** [JuliaComputing/JuliaHub#11]
https://juliahub.com/ui/Packages/Literate/XPnWG/2.4.0 is blank

**Comment by fredrikekre** [comment]
Looks like it is up now -- did the search entry update before the page was built? I suggest reversing that order.

**Comment by vdayanand** [comment]
it did update before it was built and it should be fixed.

**Comment by vdayanand** [comment]
Actually, this happened while doing maintenance work on the server and should not be a problem anymore
