### ISSUE TITLE
Package registration failed

### ISSUE THREAD

**Issue by fonsp** [JuliaComputing/JuliaHub#110]
I tried to register a package, this failed:

[screenshot](https://user-images.githubusercontent.com/6933510/114720367-4073ea80-9d38-11eb-8207-bc95ccf52ca5.png)

with an "Unexpected error"

And I was able to register the package by specifying the commit:

[screenshot](https://user-images.githubusercontent.com/6933510/114720297-3225ce80-9d38-11eb-89bc-84dccb4250b5.png)

**Comment by nkottary** [comment]
This was a race condition in updating the local registry clone when another package was registered at the same time. In Registrator.jl we avoid this by doing only one registration at a time. We should do the same in JuliaHub.
