### ISSUE TITLE
github and gitlab log ons fail

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaComputing/JuliaHub#111]
On firefox, when I go to the log in screen and click either log in with github or gitlab, at first it seems to do nothing.  If I spam click on it redirects me to
```
Bad Request

Login session expired.
```

The behavior on brave is slightly different, but I get
```
This site can’t be reachedThe webpage at https://juliahub.com/auth/login?code=XXXXXXXXXXX might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
```
when trying the same thing (I changed the has above in case it had anything to do with my gitlab account).

**Comment by pfitzseb** [comment]
Yeah, I think we ran into a similar issue before. Will investigate.

**Comment by pfitzseb** [comment]
Turns out this was a DB issue and should be fixed now.
