### ISSUE TITLE
Add DuckDuckGo bang

### ISSUE THREAD

**Issue by jonas-schulze** [JuliaComputing/JuliaHub#113]
I wanted to submit a suggestion for `!jh` as a [!bang](https://duckduckgo.com/bang) for the JuliaHub package search (`https://juliahub.com/ui/Packages?q={{{s}}}`). Part of that submission is to confirm that the new bang does not go against the terms of use of the website it links to. Unfortunately, the [terms of service](https://juliacomputing.com/terms-of-service/#restrictions_on_use) of JuliaHub point to the ones of JuliaComputing in general which would not allow a !bang like that ("make [the service] available to any third party"):

```
Restrictions on Use

In addition to all other terms and conditions set forth herein,
you shall not: (i) transfer the Software or Services or otherwise
make the same available to any third party; [...]
```

A shortcut like `!jh` would be very convenient for everyone using Julia and DuckDuckGo. I would like to ask for permission to create such a bang.

**Comment by pfitzseb** [comment]
So I'm not sure this counts as "making the Service available to any third party", but will ask for clarification.

Regardless, I'd advise you to hold off on this for a bit because we'll move to a nicer search UI in the near future (at a different URL)

**Comment by aviks** [comment]
Hi @jonas-schulze we are happy to grant permission to create DDG shortcut for JuliaHub. Thank you for doing this, this will be very useful. 

However, as Sebastian said, please consider holding off for a week or two, since the search functionality is in the process of a major revamp.

**Comment by jonas-schulze** [comment]
I've submitted the request to add `!jh` (and to update `!julia` which still points to `.../latest/...`). I don't know how quick the folks at DDG are, but if they are, and even if the update on your site takes only two weeks, the shortcut will be very useful in the meantime. I'll keep you posted. Please let me know when the revamp is ready.
