### ISSUE TITLE
Host package documentation for `dev`

### ISSUE THREAD

**Issue by fonsp** [JuliaComputing/JuliaHub#118]
juliahub offers a cool service of generating and hosting documentation for all package releases! If it would also host the `dev` version (latest `main` of `master`), then people could skip the GH actions + GH pages setup altogether and link to juliahub from their repository.

Another requirement is permanent URLs for `dev` and `latest` that people can share. Currently, URLs seem have the version number in the URL.

**Comment by pfitzseb** [comment]
It's unlikely we'll host `dev` docs, mostly because it's unclear when to update them. Setting up the proper Documenter-style symlinks is definitely planned though.
