### ISSUE TITLE
Error: Exception while getting tree SHA when registering version

### ISSUE THREAD

**Issue by jakobnissen** [JuliaComputing/JuliaHub#120]
See attached image.
The repo is here: https://github.com/jakobnissen/ErrorTypes.jl
and the tag is here: https://github.com/jakobnissen/ErrorTypes.jl/releases/tag/v0.4

![image](https://user-images.githubusercontent.com/23193950/122209394-c3cecb00-cea4-11eb-8a01-5ead68039c80.png)

**Comment by nkottary** [comment]
This is currently a bug: https://github.com/JuliaRegistries/Registrator.jl/issues/339
