### ISSUE TITLE
Missing direct dependencies

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaComputing/JuliaHub#126]
Makie seems to be missing some direct dependencies, e.g. BioMakie:
I'm guessing General is the source of truth here, which clearly shows BioMakie having Makie as a direct dependency:
https://github.com/JuliaRegistries/General/blob/master/B/BioMakie/Deps.toml#L27
The indirect dependencies also look a bit short - I think I remember seeing a much longer list in older JuliaHub versions.
Related: https://github.com/JuliaComputing/JuliaHub/issues/94

**Comment by pfitzseb** [comment]
That's working as intended: https://juliahub.com/ui/Packages/BioMakie/pb2pz/0.1.0?t=1 shows Makie in the list of dependencies, while https://juliahub.com/ui/Packages/BioMakie/pb2pz/0.2.0?t=1 doesn't, which is correct since Makie is only a dependency of BioMakie v0.1.x, not v0.2.x.

**Comment by SimonDanisch** [comment]
Hah, I guess I was parsing that TOML incorrectly, since I was convinced, that BioMakie already switched out AbstractPlotting -> Makie (but that only seems to be on master, now that I look at it more closely)...
Thanks!
