### ISSUE TITLE
Badly rendered REPL font within Brave browser

### ISSUE THREAD

**Issue by jvaverka** [JuliaComputing/JuliaHub#134]
The REPL font is rough when connecting to JuliaIDE from within the Brave browser.

![image](https://user-images.githubusercontent.com/47707103/146270605-d6633b35-528e-4883-a3b4-6d5d1e113e67.png)

This occurs with

- clean settings (empty `settings.json`)
- Brave Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (64-bit)
- Ubuntu 20.04

**Comment by pfitzseb** [comment]
Seems like this is happening due to a privacy feature: https://github.com/xtermjs/xterm.js/wiki/FAQ

Not sure what the actual option you need to disable is called.
