### ISSUE TITLE
What does "deprecated_GPL-2.0+" mean

### ISSUE THREAD

**Issue by fingolfin** [JuliaComputing/JuliaHub#14]
On various packages (e.g. <https://juliahub.com/ui/Packages/GroebnerBasis/iDGVG/0.1.0>) I've seen the license "deprecated_GPL-2.0+" -- what does that mean? What does the deprecated refer to? Is there a list of all licenses? Perhaps even a list where such a question would be answered?

**Comment by pfitzseb** [comment]
I think we're classifying licenses as per spdx.org, which lists GPL-2.0+ as deprecated: https://spdx.org/licenses/GPL-2.0+.html.

**Comment by fingolfin** [comment]
But SPDX doesn't call the license `deprecated_GPL-2.0+`. And to be frank, that they they consider it "deprecated" is all well and fine, but lots of projects use that license, e.g. the Linux kernel. 

Why not simply use the official SPDX ID and be done with it, instead of inserting value judgements?

Additionally, I am concerned that users will see "deprecated" and not understand what it relates to, and then mistakingly assume it refers to the project, not the license.

**Comment by pfitzseb** [comment]
Fair enough.

**Comment by pfitzseb** [comment]
Fixed for https://juliahub.com/ui/Packages/GroebnerBasis/iDGVG/0.1.0. The fix will propagate to the package list soon(ish).

**Comment by fingolfin** [comment]
Thank you very much!
