### ISSUE TITLE
Inline GIFs do not work in README previews

### ISSUE THREAD

**Issue by asinghvi17** [JuliaComputing/JuliaHub#17]
Consider the example of https://juliahub.com/ui/Packages/Makie/iZ1Bl/0.10.0 versus https://github.com/JuliaPlots/Makie.jl.  (In the last release the "Examples from the Documentation" section was broken, but we can ignore that for now).

These embedded images are pretty useful for plotting packages, where you need to show them off, and I can imagine a lot of other packages need this sort of thing as welll.

**Comment by asinghvi17** [comment]
On further examination, https://juliahub.com/ui/Packages/GeoMakie/GuQif/0.1.9 works well, so it seems that it's only inline GIFs which are not rendered correctly.

**Comment by vdayanand** [comment]
Fixed. Thanks for reporting.
