### ISSUE TITLE
Remove julia from dependencies?

### ISSUE THREAD

**Issue by KristofferC** [JuliaComputing/JuliaHub#19]
It seems kinda silly to have it there. It takes up quite a lot of space and it is the same everywhere.

Sure, there might be some compat bound on it but it doesn't seem worth it to show on all packages.

![image](https://user-images.githubusercontent.com/1282691/80359709-83feeb80-887e-11ea-8640-1515891bce6d.png)

**Comment by pfitzseb** [comment]
Dunno, I feel like it's valuable to know what Julia version a given package is compatible with, no?

**Comment by KristofferC** [comment]
If we really want to include it I think it should be at the very bottom, maybe only when you show version bounds and at least not be listed twice like now.

**Comment by StefanKarpinski** [comment]
It is a bit weird in that it's _always_ a dependency. Especially in the mode where we're not showing versions, it's fully redundant.

**Comment by ViralBShah** [comment]
I think that showing julia version compatibility even when not showing versions would be useful.
