### ISSUE TITLE
No syntax highlighting in READMEs

### ISSUE THREAD

**Issue by KristofferC** [JuliaComputing/JuliaHub#22]
For example https://juliahub.com/ui/Packages/ConnectFourSolver/X08Gy/0.1.0.

Compare to https://github.com/findmyway/ConnectFourSolver.jl

**Comment by pfitzseb** [comment]
Will be fixed by https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/117.

**Comment by pfitzseb** [comment]
Fixed. The change should slowly propagate through all packages as we re-generate readmes etc.
