### ISSUE TITLE
README cut off for Crayons.jl

### ISSUE THREAD

**Issue by KristofferC** [JuliaComputing/JuliaHub#23]
The README in https://juliahub.com/ui/Packages/Crayons/TXPcU/4.0.1 abruptly cuts off.

Compare to https://github.com/KristofferC/Crayons.jl/blob/master/README.md which has a much longer README.

**Comment by pfitzseb** [comment]
Probably related to the `<`. Will look into it.

**Comment by pfitzseb** [comment]
Will be fixed by https://github.com/JuliaWeb/Gumbo.jl/pull/80.

**Comment by pfitzseb** [comment]
Fixed.
