### ISSUE TITLE
Hoovering over user name when logged in shows a "weird" string

### ISSUE THREAD

**Issue by KristofferC** [JuliaComputing/JuliaHub#25]
![image](https://user-images.githubusercontent.com/1282691/80361047-8febad00-8880-11ea-8d19-be4d152d72e5.png)

**Comment by StefanKarpinski** [comment]
I believe this is the internal user ID which could be useful in some circumstances, but seems a bit too long and weird to be shown this prominently. Maybe there should be a page that's similar to the "About this Mac" box that shows this kind of debugging info that the user doesn't normally need.

**Comment by ViralBShah** [comment]
Can we do a user profile page, where this can be shown if necessary? Can also be a place to hold the user's provided information to us - that we ask for JuliaPro downloads - like company, title, etc.
