### ISSUE TITLE
Logo image for Crayons.jl broken

### ISSUE THREAD

**Issue by KristofferC** [JuliaComputing/JuliaHub#26]
https://juliahub.com/ui/Packages/Crayons/TXPcU/4.0.1

![Screenshot 2020-04-27 at 13 02 09](https://user-images.githubusercontent.com/1282691/80365127-641ff580-8887-11ea-872f-6a566a87774d.png)

The image is directed to https://juliahub.com/ui/Packages/Crayons/TXPcU/logo.png while in the repo it is directed to one of the files in the repo: https://github.com/KristofferC/Crayons.jl.

**Comment by StefanKarpinski** [comment]
Should we mirror images used in READMEs and docs so that everything is served from the same HTTPS domain?

**Comment by pfitzseb** [comment]
I'm not comfortable with mirroring images with absolute URLs (e.g. to external sites), but we're already kind of doing this for relative URLs in the repo. Just a matter of putting everything in the right place.

**Comment by pfitzseb** [comment]
Will be fixed by https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/117.

**Comment by StefanKarpinski** [comment]
I guess that if the external URL is non-HTTPS then the full site will appear insecure anyway, so our hosted docs will look insecure if-and-only-if their hosted docs appear insecure.

**Comment by pfitzseb** [comment]
It's slightly worse in the sense that even juliahub.com might appear insecure (because the readme might contain non-https content).

**Comment by StefanKarpinski** [comment]
Right, that's what I mean: our juliahub.com page will appear insecure iff their docs appear insecure, which is kind of unfortunate, but as long as the hosted docs appear secure, the corresponding juliahub.com page does too. I wonder if we could host copies of external images if we did some kind of security analysis of them first. You know that scanning that Gmail does for attachments before letting you download them? I don't mind so much for JuliaHub but for JuliaTeam, it seems like we want fully self-contained docs that don't need any external access. Low priority, but I wonder if we should make an issue to track the possibility.

**Comment by pfitzseb** [comment]
Fixed.
