### ISSUE TITLE
Image in README.md missing

### ISSUE THREAD

**Issue by newptcai** [JuliaComputing/JuliaHub#27]
![image](https://user-images.githubusercontent.com/982197/80481501-d6a9d780-8952-11ea-9686-f49b74d32aa8.png)

See here.

https://juliahub.com/ui/Packages/BeeEncoder/8OrN6/0.0.1

**Comment by pfitzseb** [comment]
Dup of https://github.com/JuliaComputing/JuliaHub/issues/26.

We're not handling relative paths in readmes correctly yet.
