### ISSUE TITLE
Add link-fragments to rendered readme

### ISSUE THREAD

**Issue by fredrikekre** [JuliaComputing/JuliaHub#29]
Similar to on GitHub: https://github.com/fredrikekre/jlpkg#usage it would be nice if this was a valid URL: https://juliahub.com/ui/Packages/jlpkg/aMH2o/1.1.3#usage

**Comment by pfitzseb** [comment]
Will be fixed by https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/117.

**Comment by pfitzseb** [comment]
Fixed. The change should slowly propagate through all packages as we re-generate readmes etc.
