### ISSUE TITLE
Unreliable search

### ISSUE THREAD

**Issue by fredrikekre** [JuliaComputing/JuliaHub#30]
I feel like i get `Server error` almost every time I visite juliahub.com
![Screenshot from 2020-04-28 16-42-08](https://user-images.githubusercontent.com/11698744/80501134-5f367100-896f-11ea-832c-1fdee38effb1.png)

**Comment by ViralBShah** [comment]
I've not got this before, but just tried and got the error.

**Comment by pfitzseb** [comment]
We've fixed a bunch of issues that could've caused these errors. Please re-open this (or open a new issue) if this happens again.
