### ISSUE TITLE
404 when trying to retrieve package information

### ISSUE THREAD

**Issue by mcabbott** [JuliaComputing/JuliaHub#32]
One of my packages doesn't show up correctly on JuliaHub:

https://juliahub.com/ui/Packages/AxisKeys/undefined/0.1.2 says "Got a 404 when trying to retrieve package information"

https://juliahub.com/ui/Logs/docs/AxisKeys/undefined/0.1.2.log?refresh=30000 gives "404 Not Found" if I try to download logs. 

https://github.com/mcabbott/AxisKeys.jl works fine, can be installed normally. It does have a folder `/docs/` with various odds & ends, but not Documenter-generated docs.

**Comment by pfitzseb** [comment]
If we don't find a make.jl file in `docs` we use the first jl we can find. Turns out there is some missing error handling in the currently deployed version which crashes everything when parsing that file fails with an error. 
I *think* that bug is fixed upstream already, but I'll double check.

**Comment by mcabbott** [comment]
OK, thanks!

Would it making an empty `make.jl` file work around this?

**Comment by pfitzseb** [comment]
Yes, but this is very clearly a bug on our side.

**Comment by pfitzseb** [comment]
Fixed.
