### ISSUE TITLE
Markdown files should be part of doc search rather than code search

### ISSUE THREAD

**Issue by tk3369** [JuliaComputing/JuliaHub#34]
I see README.md results showing up in Code Search results.  It is more intuitive to me that all markdown files are searched from the Doc Search page instead.

**Comment by pfitzseb** [comment]
We're reusing Documenter.jl's search index for doc search atm, so only markdown files used by Documenter will show up in doc search. Code search has to modes: Full text search (default) looks through all plain text files (although you can supply a regex to only search through certain files), wile Symbol Search is specific to Julia code.

Imho it's valuable to have all of those options.

**Comment by c42f** [comment]
I think it's very valuable to have full text search — it's robust and simple; reliable when more sophisticated options sometimes fail.

But IMO it's also confusing to call it "code search". IMO we should relabel it to "full text search" and provide options to filter by file extension and name.

**Comment by pfitzseb** [comment]
JuliaHub's "Code Search" tab provides both FTS *and* semantic code search (as the little blurb at the top of the page implies).

We also have a field to only search at a certain path:
https://juliahub.com/ui/Code?q=MacroTools&w=true&f=Project%5C.toml
![image](https://user-images.githubusercontent.com/6735977/84122176-5211a500-aa38-11ea-85cb-e8123964d3f6.png)

**Comment by c42f** [comment]
Right, I'm not really suggesting we change anything fundamental; only that we could add some light filtering and clarify they UI in a few places. IMHO it could make sense to separate true semantic code search from the full text search functionality. I don't think they're really the same thing.

**Comment by pfitzseb** [comment]
Fair enough. Would you suggest different pages for FTS/semantic search then?

**Comment by StefanKarpinski** [comment]
Perhaps this should be called "Repo Search"? I think that "Code Search" is entirely accurate: the README is part of the code, it's just not something that we run, but the phrase "Repo Search" makes that clear—if it's in the repo, we search it. We do have semantic code search that parses and searches Julia code specifically, which could have a separate tab. I worry about having too many search tabs though. We already have three, that would be four.

**Comment by c42f** [comment]
To me, "Code search" means "search all the `.jl` files" so I think "Repo Search" would be an improvement.

Keeping the tabs under control in the UI left hand side does seem important. On the other hand, I think it's "suspicious" that no search options are shared between FTS vs semantic search, and that indicates they're as separate from each other as they are from doc search. To me that suggests a single Search in the menu with UI subsections Documentation/Repository/Code Symbols or some such.

But perhaps that's too reductionist: users will come to the site with a task in mind. If that is *using* a package they're likely to need the documentation, but if developing a package they're more likely to use the repo search. So a more sensible split along those lines would be "Doc search" / "Dev search" or some such, with FTS/semantic search as subsections of Dev search?
