### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by yurivish** [JuliaComputing/JuliaHub#35]
Hi, this is a very cool website. 

I was wondering if the dataset powering it could be made available in a separate repository?

This would enable others to build useful tools, visualizations, and analyses on top of the package dependency graph without having to replicate the work of creating the dataset of packages with their metadata and dependencies.

**Comment by Nosferican** [comment]
Related #4.

**Comment by ViralBShah** [comment]
Let's close this one in favour of #4
