### ISSUE TITLE
dependent package not listed

### ISSUE THREAD

**Issue by goretkin** [JuliaComputing/JuliaHub#36]
`Parameters.jl` depends on `UnPack.jl` as shown here:

https://juliahub.com/ui/Packages/Parameters/ycYNs/0.12.1?t=1

However `UnPack.jl` does not list any dependents:

https://juliahub.com/ui/Packages/UnPack/zm2TF/1.0.0?t=2
![image](https://user-images.githubusercontent.com/581043/81455520-7d655380-915d-11ea-8b64-078921b52d2f.png)

I don't know what this hash is, but including in case it's useful.

![image](https://user-images.githubusercontent.com/581043/81455509-750d1880-915d-11ea-9c90-48dd41f9cd87.png)

**Comment by vdayanand** [comment]
Thanks for reporting this! it's fixed now.
