### ISSUE TITLE
Remove JuliaTagBot as a contributor

### ISSUE THREAD

**Issue by ViralBShah** [JuliaComputing/JuliaHub#38]

**Comment by pfitzseb** [comment]
Should also remove all users that have `[bot]` in their name.

**Comment by ViralBShah** [comment]
Would that have false positives? Perhaps just remove known bots for now?

**Comment by ViralBShah** [comment]
In the Julia repo, I do get a couple of false positives :
```
➜  julia git:(release-1.5) git shortlog -se | grep -i bot
     7	Michael Abbott <32575566+mcabbott@users.noreply.github.com>
    42	Stefan Kroboth <stefan.kroboth@gmail.com>
     1	femtocleaner[bot] <femtocleaner[bot]@users.noreply.github.com>
```

**Comment by ViralBShah** [comment]
Ah, if bots always have `[bot]` in their names, that seems like we can filter it out.

**Comment by pfitzseb** [comment]
Yeah, GitHub doesn't allow non-alnums (and hyphens) in user names, so this should be robust.

**Comment by ViralBShah** [comment]
Also the links for the bots don't work:

https://github.com/bors[bot]

**Comment by pfitzseb** [comment]
https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/125 allows us to do proper filtering (without relying on any heuristics).
