### ISSUE TITLE
Doesn't recognise Apache license

### ISSUE THREAD

**Issue by simonbyrne** [JuliaComputing/JuliaHub#41]
It gets marked as "UNKNOWN"
https://juliahub.com/ui/Packages/ClimateMachine/QNtDh/0.1.0

**Comment by pfitzseb** [comment]
Fixed now.

**Comment by pfitzseb** [comment]
Nevermind, the fix isn't deployed yet.

**Comment by vdayanand** [comment]
Fix is deployed
