### ISSUE TITLE
Consider filtering search results for packages in JuliaAttic

### ISSUE THREAD

**Issue by sbromberger** [JuliaComputing/JuliaHub#42]
I'm not sure directing new users to packages that are in JuliaAttic is the right approach. I don't even think these packages are guaranteed to build.

A purely selfish example: Graphs.jl is the first result when you search for "Graph". It hasn't been touched in over a year and I'm not sure it should be the recommended graph package for new users in any case (it's really complicated to use).

**Comment by vdayanand** [comment]
deployed

**Comment by sbromberger** [comment]
that was quick. Thank you.

**Comment by diegozea** [comment]
Similarly,  I found that looking for "bioinformatics" shows first the deprecated Bio.jl package. It would be great to rank lower packages that has been explicitly deprecated, for example, the ones like Bio that has the deprecated tag.
