### ISSUE TITLE
dependents package not listed

### ISSUE THREAD

**Issue by YongHee-Kim** [JuliaComputing/JuliaHub#46]
[XLSXasJSON ](https://juliahub.com/ui/Packages/XLSXasJSON/KOlLK/0.2.5?t=1 )dependens on [XLSX ](https://juliahub.com/ui/Packages/XLSX/gPxqz/0.7.2?t=2) but not listed on dependents

**Comment by ViralBShah** [comment]
XLSX is listed in Dependencies of that packages. Dependents are packages that depend on XLSXasJSON.

https://juliahub.com/ui/Packages/XLSXasJSON/KOlLK/0.2.5?t=1
