### ISSUE TITLE
PhysicsInformedML page is a 404

### ISSUE THREAD

**Issue by ViralBShah** [JuliaComputing/JuliaHub#47]
https://juliahub.com/ui/Packages/PhysicsInformedML/wQne0/0.2.0

Package page: https://github.com/TensorDecompositions/PhysicsInformedML.jl

**Comment by vdayanand** [comment]
It was taking lot of time to generate and was terminated on timeout.(https://juliahub.com/ui/Logs/docs/PhysicsInformedML/wQne0/0.2.0.log?refresh=30000) I'll try regenerating it again by increasing timeout value

**Comment by ViralBShah** [comment]
It's much simpler than many other packages, so shouldn't it be straightforward?

**Comment by pfitzseb** [comment]
It also has ~250 dependencies, some of which (apparently) take a *long* time to load/build.

**Comment by vdayanand** [comment]
Okay it worked with increased timeout.
