### ISSUE TITLE
Cannot register a new version of existing package

### ISSUE THREAD

**Issue by JockLawrie** [JuliaComputing/JuliaHub#48]
Hi there,

I am trying to release a new version of Schemata.jl.
Following the instructions at Registrator.jl, I log into JuliaHub using my GitHub credentials.
After filling in the form and pressing Submit I get this error:

`ErrorException("GitHubAPI has not implemented this function")`

Would be great to fix this as the process of registering/updating via JuliaHub is otherwise super easy.

Cheers,
Jock

**Comment by pfitzseb** [comment]
I cannot reproduce that issue. We'll look into what's going wrong in your specific case.

**Comment by pfitzseb** [comment]
Actually, did you maybe forget to increment the version number before trying to register a new version on JuliaHub?

**Comment by nkottary** [comment]
From the logs I see that the server received `https://github.com/JockLawrie/Schemata.jl/JockLawrie` as the package URL. It should be `https://github.com/JockLawrie/Schemata.jl`.

Can you try again with this correct URL?

**Comment by JockLawrie** [comment]
Hmm that's weird. Apologies.
I managed to register the new version by commenting on the commit, so
nothing to do until next release. If no one else has had this problem then
it must've been a hiccup on my part.
Thanks for attending to this

**Comment by nkottary** [comment]
No problem.
