### ISSUE TITLE
Mention DocumentationGenerator.jl in README?

### ISSUE THREAD

**Issue by tkf** [JuliaComputing/JuliaHub#49]
Does JuliaHub use DocumentationGenerator.jl? If so, maybe it's better to direct the issues related to documentation build to https://github.com/JuliaDocs/DocumentationGenerator.jl? Or maybe even mention it from the JuliaHub web app itself?

**Comment by pfitzseb** [comment]
We do mention that on the website:
![image](https://user-images.githubusercontent.com/6735977/84868217-9f1afa00-b07c-11ea-9464-5d62380b56c9.png)
