### ISSUE TITLE
License detection

### ISSUE THREAD

**Issue by fredrikekre** [JuliaComputing/JuliaHub#5]
`fredrikekre/Literate` (and many other packages) shows as `UNKNOWN` license in the search results (https://juliahub.com/ui/Packages?q=fredrikekre%2FLiterate) but as MIT when you enter the page (https://juliahub.com/ui/Packages/Literate/XPnWG/2.3.1).

**Comment by ViralBShah** [comment]
License detection is a problem on many packages. Does Github provide us an API that tells us what the license is?

**Comment by fingolfin** [comment]
Couldn't one allow Project.toml to specify a license? Possible via an [SPDX ID](https://spdx.org/ids)? Granted, that won't help now, but it could complement any automatic detection well. (And automatic detections can be wrong. For license questions, that can turn into a really expensive legal headache. Just sayin')

**Comment by pfitzseb** [comment]
License detection should be much more accurate (and consistent) now. Let's take the discussion about license IDs in Project.toml somewhere else (either the Julia or Pkg.jl repo).
