### ISSUE TITLE
Registrator web ui activation not quite smooth

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaComputing/JuliaHub#59]
I wanted to register a package with the registrator web ui for the first time since the move to juliahub. This was not entirely smooth.

* The Package URL and Package Name fields were both gray and unwilling to accept input.
* Figured I should try the "grant additional privileges" link. After a few dialogs (which probably were successful) I ended up on an error page (sorry, not available any more so can't give any details.)
* Went back to juliahub and had to make a new login, then to Registrator page and still had gray fields.
* Clicked on "grant additional privileges" again but this time I was immediately redirected to juliahub start page.
* Went back to registrator a third time and now the fields were no longer gray and everything worked.

**Comment by aviks** [comment]
This is being worked on, but there is a similar discussion in #66 so closing this.
