### ISSUE TITLE
https://www.juilahub.com certificate warning

### ISSUE THREAD

**Issue by fonsp** [JuliaComputing/JuliaHub#62]
I got this today:

![image](https://user-images.githubusercontent.com/6933510/87948329-d7ab5a80-caa4-11ea-834d-fa4e1bf75967.png)

Clicking on **View certificate**:

![image](https://user-images.githubusercontent.com/6933510/87948354-e0039580-caa4-11ea-8fb1-548cc44d998e.png)

![image](https://user-images.githubusercontent.com/6933510/87948366-e3971c80-caa4-11ea-82c2-c452572b59ed.png)

**Comment by ViralBShah** [comment]
Which URL is this on? I am not getting any warnings.

**Comment by vdayanand** [comment]
it was giving warning for `www.juliahub.com`. it is fixed now.

**Comment by StefanKarpinski** [comment]
It's for www.juliahub.com which is not the standard domain, it's JuliaHub.com. However it should redirect rather than showing a certificate error.

**Comment by fonsp** [comment]
Yes, I checked my history and it was the `www` hostname

**Comment by StefanKarpinski** [comment]
It's also in the URL bar of the screenshot, which is how I sleuthed it out as the problem 😁

**Comment by fonsp** [comment]
![image](https://user-images.githubusercontent.com/6933510/90051058-617eca00-dcd7-11ea-9a90-44157e33c4c4.png)

**Comment by ViralBShah** [comment]
Try without www. We are doing a bunch of migrations this week to CDN etc.

**Comment by fonsp** [comment]
Thanks! It's just that when you type something in the address bar, and then `Ctrl`+`Enter`, ffox and chrome redirect you to `www.whateverityped.com`. So not a major issue, but I thought i'd report it because it was fixed a few weeks ago

**Comment by ViralBShah** [comment]
Yes, let's reopen until the migration is complete and fixed and can be closed then.

**Comment by StefanKarpinski** [comment]
I believe this has happened before. Unclear to me if it was ever fixed?

**Comment by ViralBShah** [comment]
It was certainly fixed. I had checked it then.

**Comment by vdayanand** [comment]
Cloudflare url redirect doesn't seem to be working. I have handled this on the server and it should work now.
