### ISSUE TITLE
Private packages on JuliaHub?

### ISSUE THREAD

**Issue by julbinb** [JuliaComputing/JuliaHub#67]
There are about 20 packages that are searchable on JuliaHub but not accessible via GitHub (the full list is provided below). I am not sure if this is Ok or not. Those packages can't be installed via `Pkg.install` either (at least, on Julia 1.4.2):

```julia
ERROR: failed to clone from https://github.com/rjdverbeek-tud/Atmosphere.jl.git, error: GitError(Code:ERROR, Class:Net, unexpected HTTP status code: 404)
```

There is also one package called "DecentralizedInternet" which does not seem to be a Julia package at all.

Here is the full list of problematic packages:
```julia
    "https://github.com/Lonero-Team/Decentralized-Internet.git",
    # Packages below aren't publicly accessible for some reason
    "https://github.com/JuliaComputing/Blpapi.jl.git",
    "https://github.com/bcbi/CountdownLetters.jl.git",
    "https://github.com/JuliaComputing/MiletusPro.jl.git",
    "https://github.com/aramirezreyes/SAMtools.jl.git",
    "https://github.com/bcbi/CountdownNumbers.jl.git",
    "https://github.com/JuliaComputing/JuliaInXL.jl.git",
    "https://github.com/tlienart/MLJScikitLearn.jl.git",
    "https://github.com/PetrKryslUCSD/MeshKeeper.jl.git",
    "https://github.com/PetrKryslUCSD/MeshPorter.jl.git",
    "https://github.com/PetrKryslUCSD/MeshFinder.jl.git",
    "https://github.com/PetrKryslUCSD/MeshMaker.jl.git",
    "https://github.com/rjdverbeek-tud/Atmosphere.jl.git",
    "https://github.com/PumasAI/Bioequivalence.jl.git",
    "https://github.com/mrtkp9993/Bioinformatics.jl.git",
    "https://github.com/anders-dc/Granular.jl.git",
    "https://github.com/rbalexan/InfrastructureSensing.jl.git",
    "https://github.com/slmcbane/MirroredArrayViews.jl.git",
    "https://github.com/oscar-system/GAPTypes.jl.git",
    "https://github.com/StanJulia/StanMCMCChain.jl.git",
    "https://github.com/markushhh/YahooFinance.jl.git",
```

**Comment by pfitzseb** [comment]
All of those are in https://github.com/JuliaRegistries/General (I think -- didn't check all of them) and were public at some point. 

JuliaHub basically just gives you a faithful representation of the registry, so it's not clear what (if anything) we should do about this.

**Comment by StefanKarpinski** [comment]
Not much to do about this here, but I've opened an issue on the registry repo itself.

**Comment by DilumAluthge** [comment]
DecentralizedInternet is a false positive. The Julia package is in a subdirectory, which is allowed. https://github.com/Lonero-Team/Decentralized-Internet/tree/master/.julia-configs
