### ISSUE TITLE
Bad credentials error

### ISSUE THREAD

**Issue by christiankral** [JuliaComputing/JuliaHub#68]
After entirely rebooting my system I am going to https://juliahub.com/ to login with my GitHub credentials. After that I can go to https://github.com and find myself already logged in. This shows that the credentials were entered correctly.

Then I try to register a new package at https://juliahub.com/ui/Registrator. This partially worked yesterday even though the automerge process failed a couple times, see https://github.com/JuliaRegistries/General/pull/19983. However, since I made a couple attempts to re-register my new package FourierSeries.jl I always get an error message:

![image](https://user-images.githubusercontent.com/4184218/91009197-5897cd80-e5e0-11ea-8514-17c653a8c42e.png)

**Note:** I also tried to register a new package using my GitLab account which is using the same username "christiankral", see https://github.com/JuliaRegistries/General/pull/19981. May this be the reason of failing to re-register my GitHub package FourierSeries.jl

**Comment by christiankral** [comment]
@vdayanand Is this ticked closed, because the issue at JuliaHub is resolved? 

I just tried to re-register FourierSeries.jl and I still get the same error message.

**Comment by pfitzseb** [comment]
The issue is fixed, but the fix isn't deployed yet. We'll update you here when that happens.

**Comment by vdayanand** [comment]
Fix is deployed now. @christiankral can you try registering again?

**Comment by christiankral** [comment]
It now works. Thanks!
