### ISSUE TITLE
TSVD has negative star count and doesn't load

### ISSUE THREAD

**Issue by andreasnoack** [JuliaComputing/JuliaHub#7]
<img width="1070" alt="Screen Shot 2020-04-23 at 10 14 12" src="https://user-images.githubusercontent.com/505001/80075806-8940fb00-854b-11ea-9a2a-1f186aa9938e.png">
and if I click on the link I get
<img width="402" alt="Screen Shot 2020-04-23 at 10 16 27" src="https://user-images.githubusercontent.com/505001/80075837-93fb9000-854b-11ea-8883-711d36ec0eb9.png">

**Comment by StefanKarpinski** [comment]
@vdayanand, is it possible the server is still processing packages? Any idea what's going on here?

**Comment by vdayanand** [comment]
documentation generation has failed for TSVD.

**Comment by andreasnoack** [comment]
This has been fixed
