### ISSUE TITLE
Suggestion: change documentation anchor text

### ISSUE THREAD

**Issue by fonsp** [JuliaComputing/JuliaHub#71]
Currently, the link to documentation looks rather cryptic:
![image](https://user-images.githubusercontent.com/6933510/92389831-16ab7300-f11a-11ea-8dd4-78bdacfed80d.png)

I suggest to change it to:

![image](https://user-images.githubusercontent.com/6933510/92389937-465a7b00-f11a-11ea-89ec-16989fdc851a.png)

**Comment by pfitzseb** [comment]
Done. Will be released soon(ish).
