### ISSUE TITLE
Badges do not update on GitHub

### ISSUE THREAD

**Issue by scheidan** [JuliaComputing/JuliaHub#72]
The new badges look great!

So I've added a version badge to the Readme but even after several days ater a new release it does not updated on GitHub. It seem that GitHub caches the image somehow.

Probably this entry in the [GitHub documentation](https://docs.github.com/en/github/authenticating-to-github/about-anonymized-image-urls#troubleshooting-issues-with-camo) is relevant. It seems that the image header should contain a field `Cache-Control`.

**Comment by vdayanand** [comment]
Thanks for reporting this. its is fixed now.  For badges that are already cached by GitHub's image URL proxy,  follow the instruction in this link https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/about-anonymized-image-urls#removing-an-image-from-camos-cache.
