### ISSUE TITLE
Code search without regular expressions

### ISSUE THREAD

**Issue by thofma** [JuliaComputing/JuliaHub#73]
I wanted to search for
```
dirname(pathof(
```
but the search complains about "Invalid Regular Expression" and thus refuses to work. I was not trying to enter a regular expression, so this is pretty confusing. 

Maybe there should be an option to enable/disable regular expressions?

**Comment by pfitzseb** [comment]
Issue is fixed and will be deployed soon(ish).

**Comment by thofma** [comment]
Great, thanks!
