### ISSUE TITLE
Whole Word search matches parts of words

### ISSUE THREAD

**Issue by diamond-lizard** [JuliaComputing/JuliaHub#75]
I tried searching for "```midi```" with "```Whole Word```" checked:

https://juliahub.com/ui/RepoSearch?q=midi&w=true

I expected to see only results where "```midi```" matched entire words, not parts of words, but got results such as "```humidity```" and "```dehumidifier```".

**Comment by pfitzseb** [comment]
That's a bit subtle: The whole word setting only has an effect if you're using regex search, which is why the checkbox is disabled in your case. https://juliahub.com/ui/RepoSearch?q=midi&w=true&r=true gives the expected answer.

**Comment by StefanKarpinski** [comment]
Can we support whole word search in non-regex mode? It could be emulated by Regex escaping the search term and then putting `\b` before and after the escaped search term.

**Comment by pfitzseb** [comment]
Fix is in and should be deployed soon(ish).
