### ISSUE TITLE
Dependents missing

### ISSUE THREAD

**Issue by baggepinnen** [JuliaComputing/JuliaHub#78]
I'm looking at 
https://juliahub.com/ui/Packages/FillArrays/2Dg1l/0.10.0?t=2
and noticing that msote dependents are missing. I have several registered packages myself that depend on FillArrays and they are not listed.

**Comment by pfitzseb** [comment]
That's correct.
FillArrays just released 0.10.0, which not many packages are compatible with. Check out [this](https://juliahub.com/ui/Packages/FillArrays/2Dg1l/0.9.0?t=2) to see the dependents of 0.9.0.

**Comment by baggepinnen** [comment]
Ah, I didn't realize it worked like that, thanks for clarifying :)

**Comment by pfitzseb** [comment]
We've gotten a bunch of reports about this behaviour. Do you have an idea to make this more obvious or do you think we should change it to show union of the dependents of all versions by default?

**Comment by baggepinnen** [comment]
One could possible show a second section with "additional dependents of older versions"
