### ISSUE TITLE
New packages and version PRs aren’t labeled 

### ISSUE THREAD

**Issue by ericphanson** [JuliaComputing/JuliaHub#79]
I think this is a JuliaHub issue although I’m not totally sure how this works. But new package and new version PRs to the General Julia registry whose commits come from the @julpro user aren’t labeled, eg https://github.com/JuliaRegistries/General/pull/23448 vs https://github.com/JuliaRegistries/General/pull/23451. These labels are very useful for things like checking out what new packages have been registered as well as registry maintenance tasks (eg I implemented the new distance check in RegistryCI and want to keep an eye on false positives in new package registration PRs).

**Comment by aviks** [comment]
Cc @nkottary

**Comment by aviks** [comment]
Thanks for reporting this. A fix is in the works, needs testing and deployment.

**Comment by ericphanson** [comment]
Awesome! Glad to hear that.

**Comment by vdayanand** [comment]
This has been deployed
