### ISSUE TITLE
Package sidebar ideas

### ISSUE THREAD

**Issue by fredrikekre** [JuliaComputing/JuliaHub#8]
![Screenshot from 2020-04-23 14-04-11](https://user-images.githubusercontent.com/11698744/80097340-6aeaf780-856b-11ea-905a-fe412fb66c92.png)

I suggest:
 - `Version` -> `Latest version`
 -  `Documentation` should not be a link, it should show the link to the docs below, just like all other headlines in this sidebar
 - The license link should link to the file in the repository instead
 - The repository link could strip the `.git` since that is where you will be redirected to by GitHub.

**Comment by StefanKarpinski** [comment]
Agree on all points.
