### ISSUE TITLE
Tags -> topics?

### ISSUE THREAD

**Issue by timholy** [JuliaComputing/JuliaHub#82]
GitHub seems to call keywords ["topics" rather than "tags"](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/classifying-your-repository-with-topics), perhaps to distinguish them from git-tags. Is it worth adopting this terminology on the package-search tab?

**Comment by ViralBShah** [comment]
Thanks for the inputs @timholy. Do keep them flowing. Just an fyi - we tend to update these in batches as they accumulate.

**Comment by pfitzseb** [comment]
Done. The change should be deployed in a bit.
