### ISSUE TITLE
ErrorException("type User has no field login")

### ISSUE THREAD

**Issue by Volker-Weissmann** [JuliaComputing/JuliaHub#84]
Hello,
when I try to register my package, I get the error
`ErrorException("type User has no field login")`

See screenshot below.

![image](https://user-images.githubusercontent.com/39418860/101054751-84383580-3589-11eb-835f-0f06cb631f1b.png)

**Comment by vdayanand** [comment]
@Volker-Weissmann Thanks for reporting this. its fixed now. Could you try registering again?

**Comment by Volker-Weissmann** [comment]
It's working now. Thank you for fixing it.
