### ISSUE TITLE
Detect `main` vs. `master` branch automatically

### ISSUE THREAD

**Issue by eschnett** [JuliaComputing/JuliaHub#85]
The `Register packages` page auto-fills the branch name with `master`. I now have a few repositories where the main branch is `main`, and there is no `master` branch. This leads to an error message, and I then have to manually replace `master` by `main`.

It would be convenient if this page were to detect the name of the main repository branch automatically.

Alternatively, it could look at the list of previously registered packages, and continue to use the branch name listed there by default.

**Comment by StefanKarpinski** [comment]
There must be an API for getting the name of the default branch, which we should use.

**Comment by nkottary** [comment]
This was fixed in JuliaHub 5.1.0
