### ISSUE TITLE
Jobs started from VS Code Plugin stop arbitrarily

### ISSUE THREAD

**Issue by turingtest37** [JuliaComputing/JuliaHub#87]
On two occasions I have uploaded and started a job from within the VS Code plugin, then closed my laptop (without quitting VS Code) to go to sleep (a poor habit that I am trying to cut back on). The next morning I find that the job was stopped arbitrarily in the middle. No exception appears in the logs. Could this be a failed authentication check? As an example, see job

```jr-4oyjo9ikfd```

from 15 Dec 2020.

**Comment by StefanKarpinski** [comment]
Thank you for the report. We will look into it to figure out what happened.

**Comment by mdpradeep** [comment]
@turingtest37, we checked the status of this job. The time limit value for the job is set to be 5 hrs and so, the job has stopped after 5 hrs. The logs are present for those 5 hrs.

**Comment by turingtest37** [comment]
Thanks for looking into this. The 5-hour limit is suspicious, as I have been starting my jobs with a $5 spend limit, not a 5-hour time limit. I will check whether the radio button on the plug-in switches back to "by time" unexpectedly.

**Comment by mdpradeep** [comment]
You are right. This is indeed a bug. The backend was considering it as `by time` instead of `by cost`.  We will fix it soon. Meanwhile, you could re-run settting the equivalent of `$5` which works out to `8 hrs` for the job you were trying. Sorry for the inconvenience.

**Comment by mdpradeep** [comment]
@turingtest37, just FYI, this issue has been fixed and we will roll it out soon on juliahub.com. Thanks for reporting this issue.

**Comment by StefanKarpinski** [comment]
You should also have been credited back the cost of the job. Sorry about the bug and thanks for reporting!

**Comment by turingtest37** [comment]
Thank you all for building and improving this cool service!
