### ISSUE TITLE
Page navigation should be located at the bottom

### ISSUE THREAD

**Issue by fredrikekre** [JuliaComputing/JuliaHub#9]
![next-page](https://user-images.githubusercontent.com/11698744/80105819-5d3c6e80-8579-11ea-85fd-2cde3d7d0571.png)

Page navigation should be located at the bottom (or maybe both) otherwise you have to scroll all the way back up. I first thought there were no more results since there was no such button at the bottom.

**Comment by pfitzseb** [comment]
The pagination should always be on the screen, even when you scroll down.
I agree that having it at the bottom is more natural though.

**Comment by fredrikekre** [comment]
> The pagination should always be on the screen, even when you scroll down.

Yea, noticed that after, but my eyes didn't really go there naturally.

**Comment by ViralBShah** [comment]
It certainly took me some time to get my eyes to the top for pagination.
