### ISSUE TITLE
Is it possible to use julia as a software in loop for the simulation

### ISSUE THREAD

**Issue by anchasatish** [JuliaComputing/JuliaHub#91]
I would like to use Julia programming as a software in loop for my EMTDC/PSCAD or MATLAB simulation i.e., optimization problem solved in julia and output of this optimization solution is given to the Simulation platform and again output of this simulation is given as input to the julia for optimization. 
As I found some julia modules like PowerModels.jl for application of power systems optimization, I want to use same for a software in loop for my research work. If we can use julia as a software in loop, please let me know how to do it.

**Comment by StefanKarpinski** [comment]
Please ask questions at https://discourse.julialang.org.
