### ISSUE TITLE
WebUI error type Nothing has not field username

### ISSUE THREAD

**Issue by myrddin89** [JuliaComputing/JuliaHub#96]
I’m trying to register a new package hosted on GitLab and it is part of a Group/Organisation. 

I’m a bit confused about the error saying “type Nothing has not field username”. 

I logged in and authorised access. I tried different paths, like using my username on GitLab instead of the organisation name and the error is, as expected, that it cannot fetch the repository. 

So I guess the repository can be seen but at some point it fails to get all the information. Thanks for any help.

**Comment by vdayanand** [comment]
Thanks for reporting this. There was a bug, while handling repo's which are part of group, which is fixed and deployed.
